d = {}
name = input("enter the names of the friends: ")
lang = input("enter language name: ")
d.update({name: lang})
name = input("enter the names of the friends: ")
lang = input("enter language name: ")
d.update({name: lang})
name = input("enter the names of the friends: ")
lang = input("enter language name: ")
d.update({name:lang})
name = input("enter the names of the friends: ")
lang = input("enter language name: ")
d.update({name:lang})
print(d)